export default [
  {
    id: '2442449',
    date: '2022-09-26T07:00:00.000+0000',
    maxInviteeCount: 3,
    attendeeCount: 2,
    showContactInformation: false,
    contact: {
      firstName: '',
      name: '',
      email: '',
      mobile: '',
      phone: '',
      address: {},
      fullName: '',
    },
    property: {
      id: '2442379',
      name: '2 Zimmer in Stendal',
      inviteeCount: 2,
      address: {
        street: 'Karlhagenbeckstr',
        houseNumber: '31',
        city: 'Stendal',
        country: 'DE',
        zipCode: '39576',
      },
      attachments: [],
      user: {
        profile: {
          firstname: 'Max',
          name: 'Mustermann',
          phone: '',
          gender: 'NA',
          title: 'NONE',
        },
        usertype: 'COMPANYADMIN',
      },
    },
  },
  {
    id: '2442150',
    date: '2022-09-26T07:00:00.000+0000',
    maxInviteeCount: 2,
    attendeeCount: 1,
    showContactInformation: false,
    contact: {
      firstName: '',
      name: '',
      email: '',
      mobile: '',
      phone: '',
      address: {},
      fullName: '',
    },
    property: {
      id: '2440848',
      name: 'Test',
      inviteeCount: 1,
      address: {
        street: 'Lazarettstr.',
        houseNumber: '3',
        city: 'München',
        country: 'DE',
        zipCode: '80636',
      },
      attachments: [],
      user: {
        profile: {
          firstname: 'Max',
          name: 'Mustermann',
          phone: '',
          gender: 'NA',
          title: 'NONE',
        },
        usertype: 'COMPANYADMIN',
      },
    },
  },
  {
    id: '2442901',
    date: '2022-09-27T08:00:00.000+0000',
    maxInviteeCount: 3,
    attendeeCount: 1,
    showContactInformation: false,
    contact: {
      firstName: '',
      name: '',
      email: '',
      mobile: '',
      phone: '',
      address: {},
      fullName: '',
    },
    property: {
      id: '2440850',
      name: 'Flat ohne name',
      inviteeCount: 1,
      address: {
        street: 'Lazarettstr.',
        houseNumber: '3',
        city: 'München',
        country: 'DE',
        zipCode: '80636',
      },
      attachments: [],
      user: {
        profile: {
          firstname: 'Max',
          name: 'Mustermann',
          phone: '',
          gender: 'NA',
          title: 'NONE',
        },
        usertype: 'COMPANYADMIN',
      },
    },
  },
];
